#!/bin/bash

read -p "Enter the file name: " filename

# Ensure the file exists
if [ -f "$filename" ]; then
    chmod +x "$filename"
    "./$filename"
    
    read -p "Enter Commit message: " commit
    # After running the script, commit and push changes
    git add .
    git commit -m "$commit"
    git push

else
    echo "File '$filename' does not exist."
fi 
